spring.application.name=springboot
logging.level.org.springframework=info

currency-service.url=http://default.himan.com
currency-service.username=defaultusername
currency-service.key=defaultkey

management.endpoints.web.exposure.include=health,metrics

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
